trigger: 
-  main

pool: 
  name: 'Pk Pool'

stages:
-  stage: BuildStage
   displayName: "Building Application"

   jobs:
   -  job: DeveloperCoding
      displayName: "Coding"

      steps: 
      - powershell: |
         echo "Coding Accomplished"
        displayName: 'Coding Accomplished'

-  stage: TestingStage
   displayName: "Testing Application"

   jobs:
   -  job: UnitTesting
      displayName: "WhiteBox Testing"

      steps: 
      - powershell: |
         echo "Coding Accomplished"
        displayName: 'Testing Accomplished'

-  stage: DeploymentStage
   displayName: "Deploying Application"

   jobs:
   -  job: DevOpsEngineerDeployment
      displayName: "Pushing Code to Production"

      steps:
      - powershell: |
         echo "Coding Accomplished"
        displayName: 'Deployment Accomplished'
