trigger: 
-  main

pool: 
  name: 'Pk Pool'

stages:
-  stage: BuildStage
   displayName: "Building Application"

   jobs:
   -  job: DeveloperCoding
      displayName: "Coding"

      steps: 
      -  bash: |
          echo "Coding Accomplished"

-  stage: TestingStage
   displayName: "Testing Application"

   jobs:
   -  job: UnitTesting
      displayName: "WhiteBox Testing"

      steps: 
      -  bash: |
          echo "Testing Accomplished"

-  stage: DeploymentStage
   displayName: "Deploying Application"

   jobs:
   -  job: DevOpsEngineerDeployment
      displayName: "Pushing Code to Production"

      steps:
      -  bash: |
          echo "Deployment Accomplished"